### ISSUE TITLE
First click on play creates a pencil mark

### ISSUE THREAD

**Issue by ch3rryblossom** [ShivamDosajh/Maze-Solver#1]
Clicking on play on start-up seems to be marking a box right below the "Play" button with the pencil.
A very lazy fix could be to change the startup tool to an eraser lmao. 
This is amazing everywhere else tho :smiley:

https://github.com/ShivamDosajh/Maze-Solver/blob/09ba5ecca52d3409df6e6e54874e19a08fff48e6/maze_solver.py#L28-L28

**Comment by ShivamDosajh** [comment]
Heyy
Yep, I will fix that. Really glad you liked it 😁 😁
Thanks
